"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import sampling.region_data

class all_regions(object):
    __slots__ = ["num_region", "regions"]

    __typenames__ = ["int32_t", "sampling.region_data"]

    __dimensions__ = [None, ["num_region"]]

    def __init__(self):
        self.num_region = 0
        self.regions = []

    def encode(self):
        buf = BytesIO()
        buf.write(all_regions._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.num_region))
        for i0 in range(self.num_region):
            assert self.regions[i0]._get_packed_fingerprint() == sampling.region_data._get_packed_fingerprint()
            self.regions[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != all_regions._get_packed_fingerprint():
            raise ValueError("Decode error")
        return all_regions._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = all_regions()
        self.num_region = struct.unpack(">i", buf.read(4))[0]
        self.regions = []
        for i0 in range(self.num_region):
            self.regions.append(sampling.region_data._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if all_regions in parents: return 0
        newparents = parents + [all_regions]
        tmphash = (0x5116c004e56bc0af+ sampling.region_data._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if all_regions._packed_fingerprint is None:
            all_regions._packed_fingerprint = struct.pack(">Q", all_regions._get_hash_recursive([]))
        return all_regions._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

