"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class region_data(object):
    __slots__ = ["position_x", "position_y"]

    __typenames__ = ["double", "double"]

    __dimensions__ = [[2], [2]]

    def __init__(self):
        self.position_x = [ 0.0 for dim0 in range(2) ]
        self.position_y = [ 0.0 for dim0 in range(2) ]

    def encode(self):
        buf = BytesIO()
        buf.write(region_data._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>2d', *self.position_x[:2]))
        buf.write(struct.pack('>2d', *self.position_y[:2]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != region_data._get_packed_fingerprint():
            raise ValueError("Decode error")
        return region_data._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = region_data()
        self.position_x = struct.unpack('>2d', buf.read(16))
        self.position_y = struct.unpack('>2d', buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if region_data in parents: return 0
        tmphash = (0x5d252b55e1616803) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if region_data._packed_fingerprint is None:
            region_data._packed_fingerprint = struct.pack(">Q", region_data._get_hash_recursive([]))
        return region_data._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

