"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class workspace_size_data(object):
    __slots__ = ["size_x", "size_y"]

    def __init__(self):
        self.size_x = 0.0
        self.size_y = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(workspace_size_data._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">dd", self.size_x, self.size_y))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != workspace_size_data._get_packed_fingerprint():
            raise ValueError("Decode error")
        return workspace_size_data._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = workspace_size_data()
        self.size_x, self.size_y = struct.unpack(">dd", buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if workspace_size_data in parents: return 0
        tmphash = (0x8e486f48789558bc) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if workspace_size_data._packed_fingerprint is None:
            workspace_size_data._packed_fingerprint = struct.pack(">Q", workspace_size_data._get_hash_recursive([]))
        return workspace_size_data._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

