"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class sample_data(object):
    __slots__ = ["state"]

    def __init__(self):
        self.state = [ 0.0 for dim0 in range(2) ]

    def encode(self):
        buf = BytesIO()
        buf.write(sample_data._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>2d', *self.state[:2]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != sample_data._get_packed_fingerprint():
            raise ValueError("Decode error")
        return sample_data._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = sample_data()
        self.state = struct.unpack('>2d', buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if sample_data in parents: return 0
        tmphash = (0x5c4b2f699a665926) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if sample_data._packed_fingerprint is None:
            sample_data._packed_fingerprint = struct.pack(">Q", sample_data._get_hash_recursive([]))
        return sample_data._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

