/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package sampling;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class region_data implements lcm.lcm.LCMEncodable
{
    public double position_x[];
    public double position_y[];
 
    public region_data()
    {
        position_x = new double[2];
        position_y = new double[2];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x5d252b55e1616803L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(sampling.region_data.class))
            return 0L;
 
        classes.add(sampling.region_data.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 2; a++) {
            outs.writeDouble(this.position_x[a]); 
        }
 
        for (int a = 0; a < 2; a++) {
            outs.writeDouble(this.position_y[a]); 
        }
 
    }
 
    public region_data(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public region_data(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static sampling.region_data _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        sampling.region_data o = new sampling.region_data();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.position_x = new double[(int) 2];
        for (int a = 0; a < 2; a++) {
            this.position_x[a] = ins.readDouble();
        }
 
        this.position_y = new double[(int) 2];
        for (int a = 0; a < 2; a++) {
            this.position_y[a] = ins.readDouble();
        }
 
    }
 
    public sampling.region_data copy()
    {
        sampling.region_data outobj = new sampling.region_data();
        outobj.position_x = new double[(int) 2];
        System.arraycopy(this.position_x, 0, outobj.position_x, 0, 2); 
        outobj.position_y = new double[(int) 2];
        System.arraycopy(this.position_y, 0, outobj.position_y, 0, 2); 
        return outobj;
    }
 
}

